package helpers;
/**
 * @author Abraham Galindo
 * @date 12/04/2019
 * 
 */
public class HOportunidadesSolicitudHelper {
	static String[] arrPaises = {"AFGANISTAN","ALEMANIA","ALGERIA","ANGUILA","ANTARTIDA","ANTIGUA Y BARBUDA","ANTILLAS NEERLANDESAS","Arabia Saudita","ARCHIPIÉLAGO DE SVALBARD","ARGENTINA","ARMENIA","ARUBA","ASCENCIÓN","AUSTRALIA","AUSTRIA","AZERBAIJÁN","BANGLADESH","BARBADOS","BÉLGICA","BELICE","BENIN","BERMUDAS","BIELORRUSIA","BOLIVIA","BOSNIA Y HERZEGOVINA","BOTSUANA","BRASIL","BRECHOU (ISLA DEL CANAL)","BRUNEI DARUSSALAM","BULGARIA","BURKINA FASO","BURMA","BURUNDI","BUTÁN","CAMERÚN","CAMPIONE D ITALIA","CANADA","CHAD","CHILE","CHINA","CLIPPERTON","COLOMBIA","COMMONWEALTH DE DOMINICA","COMMONWEALTH DE LAS BAHAMAS","COMORAS","CONGO","COREA DEL NORTE","COREA DEL SUR","COSTA DE MARFIL","CROACIA","CUBA","DINAMARCA","E.U.A","ECUADOR","EGIPTO","EL SALVADOR","EMIRATOS ÁRABES UNIDOS","ERITREA","ESLOVAQUIA","ESLOVENIA","ESPAÑA","ESTADO DE BAHRAIN","ESTADO DE KUWAIT","ESTADO DE QATAR","ESTADO INDEPENDIENTE DE SAMOA OCCIDENTAL","ESTADO LIBRE ASOCIADO DE PUERTO RICO","ESTONIA","ETIOPÍA","FILIPINAS","FINLANDIA","FIYI","FRANCIA","GABÓN","GAMBIA","GEORGIA","GEORGIA DEL SUR E ISLAS SANDWICH DEL SUR","GHANA","GIBRALTAR","GRANADA","GRECIA","GROENLANDIA","GUADALUPE","GUAM","GUATEMALA","GUAYANA FRANCESA","GUERNESEY","GUINEA","GUINEA ECUATORIAL","GUINEA-BISSAU","HAITI","HOLANDA","HONG KONG","HUNGARIA","INDIA","INDONESIA","IRAN","IRAQ","IRLANDA","ISLA ALDERNEY","ISLA BOUVET","ISLA CAIMÁN","ISLA DE CHRISTMAS","ISLA DE GUEMESEY","ISLA DE NORFOIK","ISLA DE SAN PEDRO Y MIGUELÓN","ISLA DEL HOMBRE","ISLA GREAT SARK","ISLA HERM","ISLA JERSEY","ISLA LITTLE","ISLA QESHM","ISLANDIA","ISLAS ÅLAND","ISLAS AZORES","ISLAS CANARIAS","ISLAS COOK","ISLAS DE COCOS O KELLING","ISLAS FEROE","ISLAS HEARD Y MCDONALD","ISLAS MALVINAS","ISLAS MARIANAS DEL NORTE","ISLAS MENORES ALEJADAS DE LOS ESTADOS UNIDOS","ISLAS PACIFICO","ISLAS SALOMÓN","ISLAS TURCAS Y CAICOS","ISLAS VÍRGENES BRITÁNICAS","ISLAS VÍRGENES DE ESTADOS UNÍDOS DE AMÉRICA","ISRAEL","ITALIA","JAMAICA","JAPÓN","JETHOU LIHOU (ISLA DEL CANAL).","JORDANIA","KAZAJSTÁN","KENIA","KIRIBATÍ","LABUÁN","LAOS","LESOTHO","LETONIA","LIBANO","LIBIA","LITUANIA","LUXEMBURGO, GRAN DUCADO DE","MACAO","MACEDONIA","MADAGASCAR","MADEIRA","MALASIA","MALAWI","MALI","MALTA","MARRUECOS","MARTINICA","MAURITANIA","MAYOTTE","MEXICO","MICRONESIA","MOLDAVIA","MONGOLIA","MONTENEGRO","MONTSERRAT","MOZAMBIQUE","MYANMAR (BIRMANIA).","NAMIBIA","NEPAL","NEVIS","NICARAGUA","NÍGER","NIGERIA","NÍUE","NO DECLARADO BE","NORUEGA","NUEVA CALEDONIA","NUEVA ZELANDA","OMÁN","OTROS","PAKISTÁN","PALAOS","PAPUA NUEVA GUINEA","PARAGUAY","PATAU","PERU","PÍTCAIM","POIÍNESIA FRANCESA","POLONIA","PORTUGAL","PRINCIPADO DE ANDORRA","PRINCÍPADO DE LIECHTENSTEIN","PRINCIPADO DE MÓNACO","REÍNO DE SWAZILANDIA","REINO DE TONGA","REINO HACHEMITA DE JORDANÍA","REINO UNIDO (INGLATERRA)","REPÚBLICA CENTROAFRICANA","REPÚBLICA CHECA","REPÚBLICA DE ALBANIA","REPÚBLICA DE ANGOLA","REPÚBLICA DE CABO VERDE","REPÚBLICA DE CHIPRE","REPÚBLICA DE COSTA RICA","REPÚBLICA DE DJIBOUTI","REPÚBLICA DE GUYANA","REPÚBLICA DE HONDURAS","REPÚBLICA DE LAS ISLAS MARSHALL","REPÚBLICA DE LIBERIA","REPÚBLICA DE MALDIVAS","REPÚBLICA DE MAURICIO","REPÚBLICA DE NAURU","REPÚBLICA DE PANAMÁ","REPÚBLICA DE SEYCHELLES","REPÚBLICA DE TRINÍDAD Y TOBAGO","REPÚBLICA DE TÚNEZ","REPÚBLICA DE VANUATU","REPÚBLICA DEL YEMEN","REPÚBLICA DEMOCRÁTICA DEL CONGO","REPÚBLICA DOMINICANA","REPÚBLICA ORIENTAL DEL URUGUAY","REPÚBLICA SOCIALISTA DEMOCRÁTICA DE SRI LANKA","REUNION","RUANDA","RUMANÍA","RUSIA","SAHARA OCCIDENTAL","SAMOA AMERICANA","SAN KITTS","SAN VICENTE Y LAS GRANADINAS","SANTA ELENA","SANTA LUCÍA","SANTA SEDE / ESTADO DE LA CIUDAD DEL VATICANO","SAO TOME Y PRINCIPE","SARK (ISLA DEL CANAL)","SENEGAL","SERBIA","SERENÍSIMA REPÚBLICA DE SAN MARINO","SIERRA LEONA","SINGAPUR","SIRIA","SOMALIA","SUAZILANDIA","SUDAN","SUECIA","SUIZA","SURÁFRICA","SURINAM","TAILANDIA","TAIWÁN","TANZANIA","TAYIKISTÁN","TERRITORIO BRITANICO DEL OCEANO INDICO","TERRITORIOS AUSTRALES FRANCESES","TERRITORIOS PALESTINOS","TIMOR ORIENTAL","TOGO","TOKELAU","TRIESTE","TRISTÁN DE CUNHA","TURKMENISTÁN","TURQUÍA","TUVALU","UCRANIA","UGANDA","UZBEKISTÁN","VENEZUELA","VIETNAM","WALLIS Y FUTUNA","ZAMBIA","ZIMBABUE","ZONA ESPECIAL CANARIA","ZONA LIBRE OSTRAVA"};
	
	static int intPais = 0;
	static String strPais = "MEXICO";
	static String strNPais = "";
	
	public static String getPais()
	{
		intPais = arrPaises.length;
		for (int i=0; i<intPais;i++)
		{
			if (strPais.equals(arrPaises[i]))
			{
				strNPais = String.valueOf(i+2);
				break;				
			}
		}
		return strNPais;
	}
	
}
